### ISSUE TITLE
Missing: superlobby2 

### ISSUE THREAD

**Issue by ZaptorZap** [7RIPPY/OverloadedTeto#1]
Here's an example from [VINCEHD's userpage](https://ch.tetr.io/u/vincehd). Badge graphic is just found from https://tetr.io/res/badges/superlobby2.png

![image](https://user-images.githubusercontent.com/64891705/158117601-864e4adf-6816-40f1-9a04-70909966307d.png)

**Comment by 7RIPPY** [comment]
![image](https://user-images.githubusercontent.com/91197004/158220379-ef6217b2-c5b7-4c94-8941-e80ea8a31cac.png)
