### ISSUE TITLE
Feature: TETRA CHANNEL userpage support

### ISSUE THREAD

**Issue by ZaptorZap** [7RIPPY/OverloadedTeto#2]
It'd be pretty nice to get some sort of template for [TETRA CHANNEL](https://ch.tetr.io/) userpages, such as [mine](https://ch.tetr.io/u/zaptor). You're looking at replacing *pretty much* every single HTML element on this page so that's a tall order, but it'd be well within the scope of this project. In fact, the list of badges you already have implemented in `teto.html` is already pretty applicable to TETRA CHANNEL userpages. You just need one quick search-and-replace of `/res/badges/` with `https://tetr.io/res/badges/`:

![image](https://user-images.githubusercontent.com/64891705/158118650-0a0abe37-6927-479e-8ccf-ee50da0ab568.png)

FYI; the 5,000,000 Blast section is set to be removed as far as I know, so maybe _don't_ focus on making that look funny.

**Comment by 7RIPPY** [comment]
[Done.](https://github.com/7RIPPY/OverloadedTeto/wiki/Instructions#tetra-channel)
